WiFiClient connect timeout
arduino-libraries/WiFiNINA pull request #252
Opened 2023-09-17 20:06 UTC by JAndrassy

Following the support in the firmware in https://github.com/arduino/nina-fw/pull/89, here is the implementation of WiFiClient.connect timeout.

Additionally the strange 10 seconds waiting time is removed.

2025-03-28 10:48 UTC, pennam requested changes
Hi @JAndrassy Thanks for your contribution. I may have found a small bug, please take a look at my suggestion.

I think we should add the timeout parameter also to :

`void ServerDrv::startClient(uint32_t ipAddress, uint16_t port, uint8_t sock, uint8_t protMode)`

2025-03-28 10:48 UTC, pennam commented on src/utility/server_drv.cpp
>      int commandSize = 17 + host_len;
```suggestion
    int commandSize = 19 + host_len;
```

2025-03-28 18:02 UTC, JAndrassy commented on src/utility/server_drv.cpp
>      int commandSize = 17 + host_len;
I got it:
header 5 bytes
hostname n + 1 (terminating zero)
ipaddress 4 bytes
port 2 bytes
sock 1 byte
protmode 1 byte
timeout 2 bytes 
end mark 1 byte

17 bytes + jostlen

2025-03-28 18:07 UTC, JAndrassy commented on src/utility/server_drv.cpp
>      int commandSize = 17 + host_len;
it is 17 bytes + hostlen:
header 5 bytes
hostname n + 1 (terminating zero)
ipaddress 4 bytes
port 2 bytes
sock 1 byte
protmode 1 byte
timeout 2 bytes 
end 1 byte

2025-03-31 07:22 UTC, pennam commented on src/utility/server_drv.cpp
>      int commandSize = 17 + host_len;
The initial count seems correct, but my suggestion is wrong. It should be 20.
START CMD TOT LEN -> 3
host -> 1 + host_len
ipaddr -> 1 + 4
port -> 1 + 2
sock -> 1 + 1
protMode -> 1 + 1
timeout -> 1 + 2
END -> 1

2025-03-31 07:36 UTC, pennam commented on src/utility/server_drv.cpp
>      int commandSize = 17 + host_len;
```suggestion
    int commandSize = 20 + host_len;
```

2025-03-31 09:10 UTC, merged